version: "3"
services:
    backend:
        container_name: etereo-backend
        build: ./backend
        ports:
            - "8080:8080"
        expose:
            - 8080
        volumes:
            - ./backend:/backend
        environment:
            - PORT=8080
        command: ["npm", "start"]
    frontend:
        container_name: etereo-frontend
        build: ./frontend
        ports:
            - "8081:8080"
        expose:
            - 8081
        volumes:
            - ./frontend:/frontend
        links:
            - backend
        command: ["npm", "run", "serve"]

